apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: p-auth-core
spec:
  type: github
  address: https://github.com/loft-demos/vcp
  secretRef:
    name: loft-demo-org-cred
---
